name: Deploy Flask App

on:
  push:
    branches:
      - master  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH for Deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: root@35.176.70.5 # Replace with your EC2 public IP
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_HOST "
        cd ~/project &&
        git pull origin master &&
        pip3 install -r requirements.txt &&
        sudo systemctl restart flask_app.service
        "
